[tox]
requires =
    tox>=4
env_list =
    clean
    lint
    format
    type
    py3
    report

[testenv]
description = run unit tests
skip_install = True
deps =
    uv
commands =
    uv sync --active
    pytest --cov=src/kubebird --cov-append --cov-report=term-missing {posargs:tests}

[testenv:lint]
description = run linters
skip_install = true
deps =
    ruff
commands =
    ruff check

[testenv:format]
description = run formatter
skip_install = true
deps =
    ruff
commands = ruff format

[testenv:type]
description = run type checks
skip_install = True
deps =
    uv
commands =
    uv sync --active
    mypy {posargs:src/kubebird tests}

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase
