apiVersion: kubebird.github.io/v1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: instance-sample
spec:
  image: firebirdsql/firebird
  version: 3.0.14
  databases:
    - name: "instance.fdb"
  storage:
    primary:
      size: 3Gi
  authentication:
    sysdba:
      secretRef: instance-sample-sysdba
